"""Issue request/response schemas."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, computed_field

from app.agents.solution_advisor import parse_suggested_solution
from app.models.issue import IssueSeverity, IssueStatus


class IssueReporterBrief(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    username: str


class IssueTaskBrief(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    task_name: str


class IssueProjectBrief(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    project_code: str
    project_name: str


class IssueAdviseResponse(BaseModel):
    status: str
    message: str
    ai_run_id: int | None = None


class IssueCreate(BaseModel):
    """Manually logged problem. ``task_id`` is optional for project-level issues."""

    title: str = Field(min_length=1, max_length=300)
    description: str = Field(min_length=1, max_length=5000)
    task_id: int | None = None
    severity: IssueSeverity = IssueSeverity.MEDIUM
    status: IssueStatus = IssueStatus.OPEN


class IssueResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    project_id: int
    task_id: int | None
    reported_by: int
    title: str
    description: str
    severity: IssueSeverity
    status: IssueStatus
    suggested_solution: str | None
    created_at: datetime
    resolved_at: datetime | None
    reporter: IssueReporterBrief | None = None
    task: IssueTaskBrief | None = None
    project: IssueProjectBrief | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def suggested_solution_is_ai(self) -> bool:
        """True when suggested_solution was generated by the Solution Advisor."""
        _, is_ai = parse_suggested_solution(self.suggested_solution)
        return is_ai


class IssueUpdate(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=300)
    description: str | None = Field(default=None, min_length=1, max_length=5000)
    status: IssueStatus | None = None
    severity: IssueSeverity | None = None
    suggested_solution: str | None = Field(default=None, max_length=5000)
